## IMDB MOVIE SENTIMENT PREDICATION PROJECT

In [52]:
import numpy as np
import pandas as pd

In [53]:
# loading the dataset

In [68]:
df = pd.read_csv("C:/Users/TARUN KUMAR/Downloads/archive (8)/IMDB.csv")
print(df.head(n=5))
df = df[:10000]

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive


In [69]:
df = np.asarray(df)
X_train = df[:,0]
Y_train = df[:,1]

In [70]:
# label encoder for prediction values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y_train=le.fit_transform(Y_train)
le.classes_

array(['negative', 'positive'], dtype=object)

In [77]:
from sklearn.model_selection import train_test_split
x1_train,x1_test,y1_train,y1_test=train_test_split(X_train,Y_train,test_size=0.2)
x1_train=x1_train[:]
y1_train=y1_train[:]
x1_test=x1_test[:]
y1_test=y1_test[:]

### Cleaning Data :- Stopwords removal, Regex(punctuation) removal, Tokenization

In [78]:
from nltk.tokenize import RegexpTokenizer
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
import sys
tokenier = RegexpTokenizer(r'\w+')
en_stopwords = set(stopwords.words('english'))
ps = PorterStemmer()

In [79]:
def getCleanReview(review):
    review = review.lower()
    review = review.replace("<br /><br />"," ")
    tokens = tokenier.tokenize(review)
    new_tokens = [token for token in tokens if token not in en_stopwords]
    stemmed_tokens = [ps.stem(token) for token in new_tokens]
    cleaned_review = ' '.join(stemmed_tokens)
    return cleaned_review

In [80]:
# cleaning
x_clean = [getCleanReview(i) for i in x1_train]

In [81]:
print(x_clean)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



### Create  Vectorize Documents (CountVecotizer and TFIDF)

In [102]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [103]:
cv=CountVectorizer()
x1cv=cv.fit_transform(x1_train)

In [104]:
tfidf=TfidfVectorizer()
x1tf=tfidf.fit_transform(x1_train)

### Train a Classification Algorithm

In [105]:
# using multinomail naive bayes
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
mnb.fit(x1cv,y1_train)
mnb.score(x1cv,y1_train)

x1cv_val=cv.transform(x1_val)
x1cv_test=cv.transform(x1_test)

mnb.score(x1cv_test,y1_test)
y_pred=mnb.predict(x1cv_test)
print(y1_test)

[1 1 1 ... 1 0 0]


In [106]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y1_test, y_pred, average='binary')
from sklearn.metrics import confusion_matrix
cnf=confusion_matrix(y1_test,y_pred)
print(cnf)

[[868 130]
 [185 817]]


In [108]:
mnb1=MultinomialNB()
mnb1.fit(x1tf,y1_train)
mnb1.score(x1tf,y1_train)

x1tf_test=tfidf.transform(x1_test)
mnb1.score(x1tf_test,y1_test)
y_pred1=mnb1.predict(x1tf_test)
cnf1=confusion_matrix(y1_test,y_pred1)
print("confusion matrix : ")
print(cnf1)
precision_recall_fscore_support(y1_test, y_pred1, average='binary')

confusion matrix : 
[[885 113]
 [167 835]]


(0.880801687763713, 0.8333333333333334, 0.8564102564102564, None)